// <auto-generated />
namespace ExploreSkopjeMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class urlfblinkaddedRestaurants : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlfblinkaddedRestaurants));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201926002_url-fb-link-added-Restaurants"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
