// <auto-generated />
namespace ExploreSkopjeMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RatingCB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RatingCB));
        
        string IMigrationMetadata.Id
        {
            get { return "202012181353100_RatingCB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
