// <auto-generated />
namespace ExploreSkopjeMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class urlfblinkaddedMonuments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlfblinkaddedMonuments));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201954134_url-fb-link-added-Monuments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
