// <auto-generated />
namespace ExploreSkopjeMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class urlfacebookLinkcoffeebar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlfacebookLinkcoffeebar));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201244337_url-facebookLink-coffeebar"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
